# SPDX-License-Identifier: MIT

## Module generated by c2nim for nix_api_value.h
import
  ./nix_api_types

type
  PrimOpFun* = proc (user_data: pointer; context: NixContext; state: ptr State;
                     args: ptr Value; ret: Value)
proc alloc_value*(context: NixContext; state: State): Value {.importc: "nix_$1",
    header: "nix_api_value.h".}
proc get_type*(context: NixContext; value: Value): ValueType {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc get_typename*(context: NixContext; value: Value): cstring {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc get_bool*(context: NixContext; value: Value): bool {.importc: "nix_$1",
    header: "nix_api_value.h".}
proc get_string*(context: NixContext; value: Value): cstring {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc get_path_string*(context: NixContext; value: Value): cstring {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc get_list_size*(context: NixContext; value: Value): cuint {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc get_attrs_size*(context: NixContext; value: Value): cuint {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc get_float*(context: NixContext; value: Value): cdouble {.importc: "nix_$1",
    header: "nix_api_value.h".}
proc get_int*(context: NixContext; value: Value): int64 {.importc: "nix_$1",
    header: "nix_api_value.h".}
proc get_list_byidx*(context: NixContext; value: Value; state: State; ix: cuint): Value {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc get_attr_byname*(context: NixContext; value: Value; state: State;
                      name: cstring): Value {.importc: "nix_$1",
    header: "nix_api_value.h".}
proc has_attr_byname*(context: NixContext; value: Value; state: State;
                      name: cstring): bool {.importc: "nix_$1",
    header: "nix_api_value.h".}
proc get_attr_byidx*(context: NixContext; value: Value; state: State; i: cuint;
                     name: ptr cstring): Value {.importc: "nix_$1",
    header: "nix_api_value.h".}
proc get_attr_name_byidx*(context: NixContext; value: Value; state: State;
                          i: cuint): cstring {.importc: "nix_$1",
    header: "nix_api_value.h".}
proc set_bool*(context: NixContext; value: Value; b: bool): nix_err {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc set_string*(context: NixContext; value: Value; str: cstring): nix_err {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc set_path_string*(context: NixContext; value: Value; str: cstring): nix_err {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc set_float*(context: NixContext; value: Value; d: cdouble): nix_err {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc set_int*(context: NixContext; value: Value; i: int64): nix_err {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc set_null*(context: NixContext; value: Value): nix_err {.importc: "nix_$1",
    header: "nix_api_value.h".}
proc make_list*(context: NixContext; s: State; value: Value; size: cuint): nix_err {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc set_list_byidx*(context: NixContext; value: Value; ix: cuint; elem: Value): nix_err {.
    importc: "nix_$1", header: "nix_api_value.h".}
proc copy_value*(context: NixContext; value: Value; source: Value): nix_err {.
    importc: "nix_$1", header: "nix_api_value.h".}